# Generated by Django 3.0.2 on 2020-09-26 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200925_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
