# Generated by Django 3.0.2 on 2020-09-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='timestamp',
        ),
    ]
