# Generated by Django 3.0.2 on 2020-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_remove_actor_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
