# Generated by Django 3.0.2 on 2020-11-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0005_auto_20201021_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_ru',
        ),
    ]
