# Generated by Django 3.0.2 on 2020-09-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0004_auto_20200926_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
